### PR TITLE
Update Evaluator from Beta to Release

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
## Description

This PR updates the `evaluator` target to use the syntax of the full `openff-evaluator` release rather than the beta syntax.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by leeping** [comment]
Thank you, Simon! Time for a new FB release perhaps?

**Comment by SimonBoothroyd** [comment]
> Time for a new FB release perhaps?

That would be fantastic if all the tests come back green! 🙂

**Comment by leeping** [comment]
I'll add a few more commits for somewhat unrelated updates into this branch, followed by merging into master and then we'll make the release. :)

**Comment by SimonBoothroyd** [comment]
Sounds great! Thanks Lee-Ping!

**Pull request merged**
