### PR TITLE
[DNM] Fixes to get torsion profile target (and possibly evaluator) working again

### PR DESCRIPTION
**Pull request by j-wags**
Using this PR to iterate CI runs using a standard configuration

### CODE REVIEW

**Comment by mattwthompson** [comment]
As of commit d3397f0, the test case I [reported](https://github.com/leeping/forcebalance/issues/280#issuecomment-1405418633) appears to be fixed. It converges to slightly different values than the optimization I ran using version v1.9.3; I have no idea if these differences are notable.

```console
$ cat 1.9.3.log 1.9.4-pr-278.log
#========================================================#
#|                Optimization Converged                |#
#|            Final objective function value            |#
#|   Full:  9.885347e-03  Un-penalized:  1.365489e-04   |#
#========================================================#
#========================================================#
#|            Final optimization parameters:            |#
#========================================================#
   0 [  3.0433e-09 ] : ProperTorsions/Proper/k4/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   1 [ -4.2760e-10 ] : ProperTorsions/Proper/k1/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   2 [  6.4055e-09 ] : ProperTorsions/Proper/k2/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   3 [ -9.7498e-03 ] : ProperTorsions/Proper/k3/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
#========================================================#
#|              Final physical parameters:              |#
#========================================================#
   0 [  1.8260e-08 ] : ProperTorsions/Proper/k4/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   1 [ -2.5656e-09 ] : ProperTorsions/Proper/k1/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   2 [  3.8433e-08 ] : ProperTorsions/Proper/k2/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   3 [  1.3269e-01 ] : ProperTorsions/Proper/k3/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
----------------------------------------------------------
Backing up result/optimize/force-field.offxml -> result/optimize/force-field_23.offxml
#========================================================================#
#|  The force field has been written to the result/optimize directory.  |#
#|    Input file with optimization parameters saved to optimize.sav.    |#
#========================================================================#
Wall time since calculation start: 8.3 seconds
#========================================================#
#|                Calculation Finished.                 |#
#|      ---==(  May the Force be with you!  )==---      |#
#========================================================#
#========================================================#
#|                Optimization Converged                |#
#|            Final objective function value            |#
#|   Full:  9.885436e-03  Un-penalized:  1.365466e-04   |#
#========================================================#
#========================================================#
#|            Final optimization parameters:            |#
#========================================================#
   0 [  3.0796e-09 ] : ProperTorsions/Proper/k4/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   1 [ -4.4610e-10 ] : ProperTorsions/Proper/k1/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   2 [  6.3937e-09 ] : ProperTorsions/Proper/k2/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   3 [ -9.7499e-03 ] : ProperTorsions/Proper/k3/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
#========================================================#
#|              Final physical parameters:              |#
#========================================================#
   0 [  1.8477e-08 ] : ProperTorsions/Proper/k4/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   1 [ -2.6766e-09 ] : ProperTorsions/Proper/k1/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   2 [  3.8362e-08 ] : ProperTorsions/Proper/k2/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
   3 [  1.3269e-01 ] : ProperTorsions/Proper/k3/[#1H0X1x0!r+0A:1]-;!@[#6H3X4x0!r+0A:2](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#6H3X4x0!r+0A:3](-;!@[#1H0X1x0!r+0A])(-;!@[#1H0X1x0!r+0A])-;!@[#1H0X1x0!r+0A:4]
----------------------------------------------------------
Backing up result/optimize/force-field.offxml -> result/optimize/force-field_25.offxml
In FF.make 50 wval=1.847748009733441e-08, pid.split('/')[2]='k4'
in FF.make 51 self.openff_forcefield['ProperTorsions'].parameters[-1].k=[<Quantity(-2.67658729e-09, 'kilocalories_per_mole')>, <Quantity(3.83622522e-08, 'kilocalories_per_mole')>, <Quantity(0.132693333, 'kilocalorie / mole')>, <Quantity(1.84774801e-08, 'kilocalories_per_mole')>]
In FF.make 50 wval=-2.676587290176235e-09, pid.split('/')[2]='k1'
in FF.make 51 self.openff_forcefield['ProperTorsions'].parameters[-1].k=[<Quantity(-2.67658729e-09, 'kilocalories_per_mole')>, <Quantity(3.83622522e-08, 'kilocalories_per_mole')>, <Quantity(0.132693333, 'kilocalorie / mole')>, <Quantity(1.84774801e-08, 'kilocalories_per_mole')>]
In FF.make 50 wval=3.836225220031904e-08, pid.split('/')[2]='k2'
in FF.make 51 self.openff_forcefield['ProperTorsions'].parameters[-1].k=[<Quantity(-2.67658729e-09, 'kilocalories_per_mole')>, <Quantity(3.83622522e-08, 'kilocalories_per_mole')>, <Quantity(0.132693333, 'kilocalorie / mole')>, <Quantity(1.84774801e-08, 'kilocalories_per_mole')>]
In FF.make 50 wval=0.1326933329973879, pid.split('/')[2]='k3'
in FF.make 51 self.openff_forcefield['ProperTorsions'].parameters[-1].k=[<Quantity(-2.67658729e-09, 'kilocalories_per_mole')>, <Quantity(3.83622522e-08, 'kilocalories_per_mole')>, <Quantity(0.132693333, 'kilocalorie / mole')>, <Quantity(1.84774801e-08, 'kilocalories_per_mole')>]
#========================================================================#
#|  The force field has been written to the result/optimize directory.  |#
#|    Input file with optimization parameters saved to optimize.sav.    |#
#========================================================================#
Wall time since calculation start: 30.6 seconds
#========================================================#
#|                Calculation Finished.                 |#
#|      ---==(  May the Force be with you!  )==---      |#
#========================================================#

**Comment by j-wags** [comment]
I'm also seeing slightly different final values and different numbers of iterations when running RVK's example. It's telling that Matt's are also seeing slightly different, but consistent, outputs using our development fork. So something must still be slightly different from how 1.9.3 did things. My guesses for the remaining difference are either unit definitions (calorie to joule maybe?) or non bonded settings (like maybe pbc or cutoff. I'll look into those next.

**Comment by mattwthompson** [comment]
A detail that stands out to me is that - for this fit - the objective function converges to the same value in each case even though the final force constants are slightly different. I don't have enough experience running force field optimizations to sense if this is a stochastic and unimportant difference or a more systematic one.

**Comment by j-wags** [comment]
Hm, I get different final objective function values for the RVK case.

Using "new env":
```
#========================================================#
#|                Optimization Converged                |#
#|            Final objective function value            |#
#|   Full:  1.524099e-01  Un-penalized:  6.714228e-02   |#
#========================================================#
```

using "old env"
```
#========================================================#
#|                Optimization Converged                |#
#|            Final objective function value            |#
#|   Full:  1.591332e-01  Un-penalized:  7.196531e-02   |#
#========================================================#
```

**Comment by j-wags** [comment]
My mistake was that the "old env" didn't have OpenEye. Fixing that, they now produce nearly identical results (like, to 1e-4 kcal/mol) on the RVK case. They also produce similarly identical results both using AmberTools.

**Pull request closed without merging**
