### PR TITLE
Migrate from PropertyEstimator to OpenFF Evaluator

### PR DESCRIPTION
**Pull request by SimonBoothroyd**
## Description

This PR handles the migration from the soon to be deprecated `propertyestimator` package to the rebranded `openff-evaluator` package. There are a number of API changes and improvements introduced in the new package which are reflected in this PR.

This main changes introduced by this PR are:

- code now refers to `propertyestimator` as `openff-evaluator` (as well as variants on this, e.g PropertyEstimator -> Evaluator).

- data sets are no longer partitioned into dictionaries, but are kept as data set objects. Reference and target property pairs are now determined by the properties unique id.

- targets have been updated to use the current evaluator syntax.

- default units of different properties are now determined from the denominators provided in the options file to allow greater flexibility (i.e no more hard-coding).

The tests are expected to skip / fail until the `openff-evaluator` beta package is released early next week (Mon / Tues).

The intention is to use this updated code as part of the upcoming VdW refit feasibility studies so it would be good to get this merged in as soon as convenient.

## Status
- [X] Ready to review
- [x] Ready to merge

### CODE REVIEW

**Comment by j-wags** [comment]
Diff of `property_estimator_io.py` and `evaluator.py`: https://www.diffchecker.com/cNJR9jXJ

**Comment by SimonBoothroyd** [comment]
Ok the evaluator tests seems to be passing now (the failures appear to be unrelated).

**Comment by leeping** [comment]
This looks excellent; thank you! Could you rename the module `evaluator.py` to `evaluator_io.py`?  At the moment, that is the naming convention used for modules that communicate with software for target evaluation.

**Comment by SimonBoothroyd** [comment]
> Could you rename the module evaluator.py to evaluator_io.py?

Absolutely - this is fixed in cb70ecb

**Comment by leeping** [comment]
Thank you! I'm merging now. Let me know separately if a new release is needed.

**Pull request merged**
