### PR TITLE
Optimized geo target

### PR DESCRIPTION
**Pull request by yudongqiu**

### CODE REVIEW

**Comment by yudongqiu** [comment]
This PR mainly includes the implementation of the Optimized Geometry Target

**Comment by leeping** [comment]
Thank you very much!  I've merged the new feature and may make some future minor adjustments.

**Comment by yudongqiu** [comment]
The new target type is `OptGeoTarget_OpenMM` or `OptGeoTarget_SMIRNOFF`.

The examples are put as `studies/022_opt_geo_target`

Note: The input and output files of this example were generated using `openforcefield 0.0.4` and `smirnoff99Frosst.offxml` 0.1.

**Comment by leeping** [comment]
I know this is already closed, but could we change the target name to `OptGeo_<engine>` and shorten the field name `optgeo_options_txt` to `optgeo_txt`?

**Comment by yudongqiu** [comment]
Sure we can do that in the next PR.

**Comment by leeping** [comment]
This pull request **introduces 5 alerts** when merging d11985a4fd667105b61ae194c84ffa27156ee372 into 2b7370c476630aabeb454e29d31687af2db51da1 - [view on LGTM.com](https://lgtm.com/projects/g/leeping/forcebalance/rev/pr-7f3c31e3bbbd8682869c249015f5c6ab0bed8ecc)

**new alerts:**

* 5 for Unused import

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
